version: '3'
services:
  db:
    image: mysql:8.0
    container_name: 'lt-db'
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d # 初期データ
      - ./mysql/conf:/etc/mysql/conf.d # 設定ファイル
      - ./mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: khcoder
      MYSQL_USER: khcoder
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    ports:
      - '3306:3306'
    restart: always

  khcoder:
    container_name: 'khcoder'
    build:
      context: .docker
      dockerfile: khcoder.dockerfile
    ports:
      - '3333:3333'
    environment:
        DISPLAY: $DISPLAY
    volumes:
      - './KHCoder:/KHCoder'
      - '$HOME/.Xauthority:/root/.Xauthority'
    command: xeyes

  twitter-py:
    container_name: 'twitter-py'
    build:
      context: .docker
      dockerfile: twitter-py.dockerfile
